### ISSUE TITLE
Paint v trips

### ISSUE THREAD

**Issue by hay216** [SteveLane/blistering-barnacles#6]
Steve - please check the relationship between median number of trips and ablative/self polishing paint types - Figure 6 and Figure 2b show a clear relationship between median number of trips and self-polishing and ablative paints but not hard paints - this is should be acknowledged in the results section and discussion

**Comment by SteveLane** [comment]
@hay216 I don't buy it! Not that the other possible interaction is huge, but compared to that this one seems small!
If you think it's important (especially storywise) I'll develop a new model.

**Comment by hay216** [comment]
Yeah – story wise its important – ablative and self-polishing paints only work if you actually use the vessel so would expect an interaction between these two paint types and midTrips – hard paints doesn’t matter so here you wouldn’t expect and interaction – the results do seem to back this up (even if slightly) ?]

K

**Comment by SteveLane** [comment]
That's why we've got you! I did set that model off and running in the meantime... still waiting for it to finish...

**Comment by hay216** [comment]
Legend – thx Steve – I should try and stop by CEBRA one day – are you going to the ANZ-SRA conference in Nov?

K

**Comment by SteveLane** [comment]
I'll be there 👍 
I'll let you know once the model is updated

**Comment by SteveLane** [comment]
@hay216 - revisiting this. I've run an extra model, but I'm not sure it's needed. If you see a possible interaction between mid trips and paint types, then I think there's also a possible relationship between mid trips and vessel type. What do you think? In this case, we'd just fall back to M3.

**Comment by hay216** [comment]
That's plausible - commercial (fishing) vessels likely to be more active than recreational (yachts or motor cruisers) vessels?.
